version: "3.3"
services:
  control:
    image: ami:latest
    build:
      context: ./docker
      dockerfile: Dockerfile
    container_name: control 
    hostname: control
    volumes:
       - ./ansible:/home/ec2-user/ansible
    networks:
      - ansiblenet
  server:
    image: ami:latest
    hostname: server
    container_name: server 
    networks:
      - ansiblenet 
  server_2:
    image: ami:latest
    hostname: server
    container_name: server_2 
    networks:
      - ansiblenet 
networks:
  ansiblenet:
    driver: bridge
    ipam:
      driver: default

